### PR TITLE
Improvement/update to tldextract 2.0.1

### PR DESCRIPTION
**Pull request by douglas**

### CODE REVIEW

**Comment by douglas** [comment]
Hopefully, fixes #29.

**Comment by snormore** [comment]
cc @CamDavidsonPilon @JamesOwenHall

**Comment by snormore** [comment]
This looks good to me, thanks for the update @douglas 👍

**Comment by JamesOwenHall** [comment]
👍

**Comment by snormore** [comment]
Could you bump the version in https://github.com/Shopify/pyreferrer/blob/master/setup.py#L4 for this as well?

**Comment by douglas** [comment]
Hello @snormore!

Just updated the version in setup.py =)

Is there anything else that I can help with?

**Comment by snormore** [comment]
Thanks again for the update @douglas !

**Pull request merged**
