### PR TITLE
Account for null byte in url

### PR DESCRIPTION
**Pull request by arthurprevot**
To solve https://github.com/Shopify/pyreferrer/issues/26
@CamDavidsonPilon @snormore @drdee @bani @samtalasila

### CODE REVIEW

**Comment by snormore** [comment]
👍 ❤️

**Comment by CamDavidsonPilon** [comment]
Thanks for contributing to opensource!

**Comment by arthurprevot** [comment]
Thanks. I guess we should bump up the version is the starscream requirements, right ?

**Comment by drdee** [comment]
This seems a quite slow implementation....

**Comment by arthurprevot** [comment]
True. Alternative I see is :
```
raw_url = raw_url.strip()
raw_url = raw_url.decode("utf-8").replace('\x00', '').encode("utf-8") if '\x00' in raw_url else raw_url
```
Let me know if you can think of something better.

**Comment by arthurprevot** [comment]
mmm, forget my suggestion, it doesn't pass the tests because the `if '\x00' in raw_url` part would require decoding the string anyway..

**Comment by CamDavidsonPilon** [comment]
@arthurprevot sorry to bring this back up*, but does this belong in pyreferrer, or should the builder handle cases like this? 

*🍁

**Comment by arthurprevot** [comment]
We already handle the problem in the builder, but I thought the problem should ideally be fixed in the library that made the job fail..

**Comment by CamDavidsonPilon** [comment]
Hm, so this is a software question. @snormore @drdee what do you two think?

**Comment by snormore** [comment]
I think it's 👌 and makes sense to handle this in pyreferrer, otherwise all users of the library has to find this out on their own and patch their code.

**Comment by bani** [comment]
I think this is a good temporary solution but we should try to push it further downstream to the library that actually caused the error. Let's see what they say if we submit a patch.

**Comment by snormore** [comment]
@bani agreed, good call 👍

**Comment by arthurprevot** [comment]
https://github.com/john-kurkowski/tldextract/issues/96

**Pull request merged**
